name: Schedule Leaderboard Update

on:
  schedule:
    - cron: '30 13 * * 5,6'
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Update Leaderboard
        run: |
          curl -X POST https://pointblank.club/api/hustle
